name: Build and Deploy
on:
  push:	
    branches:	
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Hexo Action
      uses: sma11black/hexo-action@v1.0.4
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        user_name: yangxiaolang  # (or delete this input setting to use bot account)
        user_email: 1810849666@qq.com  # (or delete this input setting to use bot account)